sudo: required

env:
- GHCVER=8.0.2
- GHCVER=8.2.2
- GHCVER=8.4.4
- GHCVER=8.6.1
- GHCVER=head

script:
- curl -sSL https://raw.github.com/tomjaguarpaw/neil/stable4/travis.sh | sh -s tomjaguarpaw stable4

# To clear the caches go to
#
#     https://travis-ci.org/tomjaguarpaw/haskell-opaleye/caches
#
# (or the equivalent where you run Travis)
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

before_script:
- export POSTGRES_CONNSTRING="user='postgres' dbname='opaleye_test'"
- psql -c 'create database opaleye_test;' -U postgres

addons:
  postgresql: "9.5"
